import type { IconType } from "react-icons"
import {
  MdAdd,
  MdCancel,
  MdCheck,
  MdCheckCircle,
  MdClose,
  MdDelete,
  MdEdit,
  MdGroup,
  MdHome,
  MdInfo,
  MdInsertDriveFile,
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdKeyboardArrowUp,
  MdLock,
  MdLockOpen,
  MdMoreHoriz,
  MdMoreVert,
  MdNotifications,
  MdOutlineCancel,
  MdOutlineCheckCircle,
  MdOutlineDelete,
  MdOutlineEdit,
  MdOutlineGroup,
  MdOutlineHome,
  MdOutlineInfo,
  MdOutlineInsertDriveFile,
  MdOutlineLock,
  MdOutlineLockOpen,
  MdOutlineNotifications,
  MdOutlinePerson,
  MdOutlineSearch,
  MdOutlineSettings,
  MdOutlineVisibility,
  MdOutlineVisibilityOff,
  MdOutlineWarning,
  MdPerson,
  MdRemove,
  MdSearch,
  MdSettings,
  MdVisibility,
  MdVisibilityOff,
  MdWarning,
} from "react-icons/md"

export const iconMap = {
  "bell": MdNotifications,
  "bell-outline": MdOutlineNotifications,
  "check": MdCheck,
  "check-circle": MdCheckCircle,
  "check-circle-outline": MdOutlineCheckCircle,
  "chevron-down": MdKeyboardArrowDown,
  "chevron-left": MdKeyboardArrowLeft,
  "chevron-right": MdKeyboardArrowRight,
  "chevron-up": MdKeyboardArrowUp,
  "dots-horizontal": MdMoreHoriz,
  "dots-vertical": MdMoreVert,
  "eye": MdVisibility,
  "eye-off": MdVisibilityOff,
  "eye-off-outline": MdOutlineVisibilityOff,
  "eye-outline": MdOutlineVisibility,
  "file": MdInsertDriveFile,
  "file-outline": MdOutlineInsertDriveFile,
  "gear": MdSettings,
  "gear-outline": MdOutlineSettings,
  "home": MdHome,
  "home-outline": MdOutlineHome,
  "info": MdInfo,
  "info-outline": MdOutlineInfo,
  "lock": MdLock,
  "lock-outline": MdOutlineLock,
  "minus": MdRemove,
  "pen": MdEdit,
  "pen-outline": MdOutlineEdit,
  "plus": MdAdd,
  "search": MdSearch,
  "search-outline": MdOutlineSearch,
  "trash": MdDelete,
  "trash-outline": MdOutlineDelete,
  "unlock": MdLockOpen,
  "unlock-outline": MdOutlineLockOpen,
  "user": MdPerson,
  "user-outline": MdOutlinePerson,
  "users": MdGroup,
  "users-outline": MdOutlineGroup,
  "warning": MdWarning,
  "warning-outline": MdOutlineWarning,
  "x": MdClose,
  "x-circle": MdCancel,
  "x-circle-outline": MdOutlineCancel,
} satisfies Record<string, IconType>

export type IconName = keyof typeof iconMap
