import type { IconType } from "react-icons"
import {
  MdAdd,
  MdAttachMoney,
  MdCancel,
  MdCheck,
  MdCheckCircle,
  MdClose,
  MdDashboard,
  MdDelete,
  MdEdit,
  MdGroup,
  MdHome,
  MdInfo,
  MdInsertDriveFile,
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdKeyboardArrowUp,
  MdLabel,
  MdLock,
  MdLockOpen,
  MdMoreHoriz,
  MdMoreVert,
  MdNotifications,
  MdOutlineAttachMoney,
  MdOutlineCancel,
  MdOutlineCheckCircle,
  MdOutlineDashboard,
  MdOutlineDelete,
  MdOutlineEdit,
  MdOutlineGroup,
  MdOutlineHome,
  MdOutlineInfo,
  MdOutlineInsertDriveFile,
  MdOutlineLabel,
  MdOutlineLock,
  MdOutlineLockOpen,
  MdOutlineNotifications,
  MdOutlinePerson,
  MdOutlineSearch,
  MdOutlineSettings,
  MdOutlineStarOutline,
  MdOutlineVisibility,
  MdOutlineVisibilityOff,
  MdOutlineWarning,
  MdPerson,
  MdRemove,
  MdSearch,
  MdSettings,
  MdStar,
  MdVisibility,
  MdVisibilityOff,
  MdWarning,
} from "react-icons/md"

export const iconMap = {
  bell: MdNotifications,
  "bell-outline": MdOutlineNotifications,
  check: MdCheck,
  "check-circle": MdCheckCircle,
  "check-circle-outline": MdOutlineCheckCircle,
  "chevron-down": MdKeyboardArrowDown,
  "chevron-left": MdKeyboardArrowLeft,
  "chevron-right": MdKeyboardArrowRight,
  "chevron-up": MdKeyboardArrowUp,
  dashboard: MdDashboard,
  "dashboard-outline": MdOutlineDashboard,
  "dots-horizontal": MdMoreHoriz,
  "dots-vertical": MdMoreVert,
  eye: MdVisibility,
  "eye-off": MdVisibilityOff,
  "eye-off-outline": MdOutlineVisibilityOff,
  "eye-outline": MdOutlineVisibility,
  file: MdInsertDriveFile,
  "file-outline": MdOutlineInsertDriveFile,
  gear: MdSettings,
  "gear-outline": MdOutlineSettings,
  home: MdHome,
  "home-outline": MdOutlineHome,
  info: MdInfo,
  "info-outline": MdOutlineInfo,
  label: MdLabel,
  "label-outline": MdOutlineLabel,
  lock: MdLock,
  "lock-outline": MdOutlineLock,
  minus: MdRemove,
  money: MdAttachMoney,
  "money-outline": MdOutlineAttachMoney,
  pen: MdEdit,
  "pen-outline": MdOutlineEdit,
  plus: MdAdd,
  search: MdSearch,
  "search-outline": MdOutlineSearch,
  star: MdStar,
  "star-outline": MdOutlineStarOutline,
  trash: MdDelete,
  "trash-outline": MdOutlineDelete,
  unlock: MdLockOpen,
  "unlock-outline": MdOutlineLockOpen,
  user: MdPerson,
  "user-outline": MdOutlinePerson,
  users: MdGroup,
  "users-outline": MdOutlineGroup,
  warning: MdWarning,
  "warning-outline": MdOutlineWarning,
  x: MdClose,
  "x-circle": MdCancel,
  "x-circle-outline": MdOutlineCancel,
} satisfies Record<string, IconType>

export type IconName = keyof typeof iconMap
